const $ = (selector) => document.querySelector(selector);
const $$ = (selector) => [...document.querySelectorAll(selector)];

function svgData(svg) { return `data:image/svg+xml;charset=UTF-8,${encodeURIComponent(svg)}`; }
function bookCover(title, subject, hue) {
  return svgData(`<svg xmlns="http://www.w3.org/2000/svg" width="280" height="380"><defs><linearGradient id="g" x2="1" y2="1"><stop stop-color="hsl(${hue} 55% 94%)"/><stop offset="1" stop-color="hsl(${hue} 70% 72%)"/></linearGradient></defs><rect width="280" height="380" fill="url(#g)"/><rect x="14" y="14" width="252" height="352" rx="4" fill="none" stroke="hsl(${hue} 48% 40%)" stroke-width="2"/><circle cx="140" cy="132" r="58" fill="hsl(${hue} 55% 55%)" opacity=".18"/><path d="M78 175 Q140 105 202 175 Q140 226 78 175" fill="hsl(${hue} 54% 45%)" opacity=".2"/><text x="140" y="66" text-anchor="middle" font-family="sans-serif" font-size="17" fill="#425466">同步练习册</text><text x="140" y="258" text-anchor="middle" font-family="sans-serif" font-size="25" font-weight="bold" fill="#22384a">${title}</text><text x="140" y="289" text-anchor="middle" font-family="sans-serif" font-size="16" fill="#526b7c">${subject}</text><rect x="82" y="315" width="116" height="22" rx="11" fill="#fff" opacity=".65"/><text x="140" y="331" text-anchor="middle" font-family="sans-serif" font-size="11" fill="#5c6e7c">名校课堂 · 新版</text></svg>`);
}
function answerPage(index, hue = 211) {
  const lines = Array.from({length: 16}, (_, i) => `<rect x="${i % 4 === 0 ? 82 : 52}" y="${110 + i * 42}" width="${510 - (i % 3) * 50}" height="3" rx="1" fill="#d8dde2"/><text x="55" y="${100 + i * 42}" font-family="serif" font-size="14" fill="#66717b">${i + 1}. ${i % 2 ? '请根据题意完成下列问题，并写出解答过程。' : '填空：________________________'}</text>`).join('');
  return svgData(`<svg xmlns="http://www.w3.org/2000/svg" width="700" height="980"><rect width="700" height="980" fill="#fff"/><rect x="28" y="25" width="644" height="930" fill="none" stroke="#d3d8dc"/><rect x="28" y="25" width="644" height="62" fill="hsl(${hue} 45% 94%)"/><text x="52" y="64" font-family="sans-serif" font-size="22" font-weight="bold" fill="#304657">课后练习答案 · 第 ${index} 页</text><text x="625" y="64" text-anchor="end" font-family="sans-serif" font-size="13" fill="#768593">用户上传原图</text>${lines}<path d="M455 740q55-70 115 0t80 20" fill="none" stroke="hsl(${hue} 55% 52%)" stroke-width="4" opacity=".5"/><text x="615" y="915" text-anchor="end" font-family="serif" font-size="17" fill="#7c8790">${index}</text></svg>`);
}

const books = [
  {id:'UGC2609070018',name:'名校课堂同步练习册',subtitle:'下册',textbookVersion:'人教版',isbn:'9787575424851',grade:'八年级',course:'历史',province:'浙江省',userId:'256039654',uploader:'林溪同学',time:'2026-09-07 20:02',status:'AI审核未通过',remark:'检测到违规内容',aiResult:'单图审核输出 1',hue:12,images:16},
  {id:'UGC2609070017',name:'阳光同学课时优化作业',subtitle:'上册',textbookVersion:'苏教版',isbn:'9787107416453',grade:'四年级',course:'语文',province:'江苏省',userId:'1063843067',uploader:'星星妈妈',time:'2026-09-07 19:46',status:'待人工审核',remark:'',aiResult:'整体判断结果 0.92',hue:38,images:18},
  {id:'UGC2609070016',name:'实验班提优训练',subtitle:'全册',textbookVersion:'人教版',isbn:'9787577433312',grade:'九年级',course:'物理',province:'广东省',userId:'832760142',uploader:'陈知远',time:'2026-09-07 18:21',status:'AI审核未通过',remark:'上传图片非答案内容',aiResult:'单图审核输出 2',hue:148,images:16},
  {id:'UGC2609070015',name:'计算能手每日一练',subtitle:'上册',textbookVersion:'北师大版',isbn:'9787568892018',grade:'五年级',course:'数学',province:'四川省',userId:'505120083',uploader:'小麦同学',time:'2026-09-07 17:35',status:'审核通过',remark:'',aiResult:'整体判断结果 0.95',newBookId:'5048584',hue:205,images:22},
  {id:'UGC2609070014',name:'新概念英语同步测试',subtitle:'上册',textbookVersion:'外研版',isbn:'9787544988278',grade:'七年级',course:'英语',province:'山东省',userId:'781044592',uploader:'Summer',time:'2026-09-07 16:08',status:'人工审核未通过',remark:'答案图片缺少第 12 页，请补充后重新上传',aiResult:'整体判断结果 0.88',hue:258,images:11},
  {id:'UGC2609070013',name:'课堂作业本',subtitle:'上册',textbookVersion:'浙教版',isbn:'9787553694719',grade:'六年级',course:'数学',province:'浙江省',userId:'610552741',uploader:'一叶知秋',time:'2026-09-07 15:42',status:'待人工审核',remark:'',aiResult:'整体判断结果 0.91',hue:325,images:16},
  {id:'UGC2609070012',name:'语文知识集锦',subtitle:'上册',textbookVersion:'苏教版',isbn:'9787544560900',grade:'三年级',course:'语文',province:'江苏省',userId:'391527004',uploader:'橙子爸爸',time:'2026-09-07 14:33',status:'审核通过',remark:'',aiResult:'整体判断结果 0.93',newBookId:'5048612',hue:50,images:20},
  {id:'UGC2609070011',name:'培优新帮手',subtitle:'上册',textbookVersion:'人教版',isbn:'9787535182722',grade:'八年级',course:'数学',province:'广东省',userId:'294771038',uploader:'晚风',time:'2026-09-07 13:17',status:'AI审核未通过',remark:'答案不完整',aiResult:'整体判断结果 0.73',hue:187,images:16}
];
books.forEach((b, i) => { b.cover = bookCover(b.name.slice(0, 6), `${b.grade} · ${b.course}`, b.hue); b.pages = Array.from({length:b.images}, (_, j) => ({id:`${b.id}-${j+1}`,src:answerPage(j+1,b.hue),rotation:0,crop:{top:0,right:0,bottom:0,left:0}})); });
let filteredBooks = [...books]; let currentBook = null; let currentImageIndex = 0; let editMode = false; let pendingDecision = null; let draggedIndex = null; let cropDraft = null; let cropPreview = false; let orderSnapshot = null;
const statusClass = {'AI审核未通过':'rejected','待人工审核':'pending','人工审核未通过':'rejected','审核通过':'passed'};
const cropInset = crop => `inset(${crop.top}% ${crop.right}% ${crop.bottom}% ${crop.left}%)`;
const isCropped = crop => Object.values(crop).some(value => value > 0);
const canModifyCurrentBook = () => currentBook?.status === '待人工审核';

function renderRows() {
  $('#bookRows').innerHTML = filteredBooks.map(book => `<tr>
    <td><code>${book.id}</code></td>
    <td><div class="book-cell"><img class="cover" src="${book.cover}" alt=""><div class="book-cell-content"><div class="book-name">${book.name}</div><div class="book-tag-rows"><div class="book-tags"><span>${book.textbookVersion}</span><span>${book.province}</span></div><div class="book-tags"><span>${book.course}</span><span>${book.grade}</span><span>${book.subtitle}</span></div></div></div></div></td>
    <td>${book.isbn}</td>
    <td><div class="uploader"><strong>${book.uploader}</strong><span>ID：${book.userId}</span></div></td>
    <td>${book.time.replace(' ','<br>')}</td><td><span class="status ${statusClass[book.status]}">${book.status}</span></td>
    <td class="remark-cell">${book.remark || '—'}</td>
    <td><button class="action-link review-action" data-id="${book.id}">${book.status==='待人工审核'?'审核':'查看'}</button></td>
    <td>${book.newBookId?`<a class="new-book-link" href="https://merc.yuanfudao.com/mark-qs/book/list?source=1&amp;ids=${encodeURIComponent(book.newBookId)}" target="_blank" rel="noopener noreferrer">${book.newBookId}</a>`:'—'}</td></tr>`).join('');
  $('#resultCount').textContent = filteredBooks.length; $('#paginationCount').textContent = filteredBooks.length;
  $$('.review-action').forEach(btn => btn.addEventListener('click', () => openDetail(btn.dataset.id)));
}
function updateSummaries() {
  const count = s => books.filter(b=>b.status===s).length;
  $('#summaryAiRejected').textContent=count('AI审核未通过'); $('#summaryPending').textContent=count('待人工审核');
}
function openDetail(id) {
  currentBook=books.find(b=>b.id===id); if(!currentBook)return; currentImageIndex=0; editMode=false;
  $('#listView').classList.remove('active'); $('#detailView').classList.add('active'); window.scrollTo(0,0);
  $('#detailTitle').textContent=currentBook.name; $('#detailId').textContent=currentBook.id; $('#detailCover').src=currentBook.cover; $('#detailBookName').textContent=`${currentBook.name} · ${currentBook.subtitle}`;
  ['Isbn','TextbookVersion','Subtitle','Grade','Course','Province','UserId','Uploader','Time'].forEach(k=>$('#detail'+k).textContent=currentBook[k.charAt(0).toLowerCase()+k.slice(1)]);
  const st=$('#detailStatus'); st.textContent=currentBook.status; st.className=`status ${statusClass[currentBook.status]}`;
  const reviewable=currentBook.status==='待人工审核';
  $('#editBookInfo').classList.toggle('hidden',!reviewable); $('#bookInfoEditor').classList.add('hidden'); $('#bookInfoDisplay').classList.remove('hidden');
  $('#toggleEdit').classList.toggle('hidden',!reviewable); $('#viewerToolbar').classList.toggle('hidden',!reviewable); $('#decisionActions').classList.toggle('hidden',!reviewable); $('#autosaveText').innerHTML=reviewable?'<span class="dot"></span> 图书信息和图片调整自动保存在本次演示中':'当前任务仅支持查看'; setEditMode(false); renderThumbnails();
}
function renderThumbnails() {
  const canReorder=editMode&&canModifyCurrentBook();$('#imageCount').textContent=currentBook.pages.length; const grid=$('#thumbnailGrid'); grid.classList.toggle('editing',canReorder);
  grid.innerHTML=currentBook.pages.map((page,i)=>{const sideways=Math.abs(page.rotation)%180===90;return `<div class="thumb ${i===currentImageIndex?'selected':''}" draggable="${canReorder}" data-index="${i}"><img class="${sideways?'rotated-sideways':''}" style="transform:rotate(${page.rotation}deg) scale(${sideways?'.72':'1'});clip-path:${cropInset(page.crop)}" src="${page.src}" alt="第 ${i+1} 张答案图片"><span class="thumb-no">${i+1}</span>${isCropped(page.crop)?'<span class="thumb-cropped">已裁切</span>':''}<span class="thumb-drag">⠿</span></div>`;}).join('');
  $$('.thumb').forEach(el=>{
    el.addEventListener('click',()=>{currentImageIndex=Number(el.dataset.index);renderThumbnails();openViewer();});
    el.addEventListener('dragstart',e=>{if(!canReorder){e.preventDefault();draggedIndex=null;return;}draggedIndex=Number(el.dataset.index);});
    el.addEventListener('dragover',e=>{if(canReorder)e.preventDefault();});
    el.addEventListener('drop',e=>{if(!canReorder||!canModifyCurrentBook()){draggedIndex=null;return;}e.preventDefault();const to=Number(el.dataset.index);if(draggedIndex===null||draggedIndex===to)return;const [moved]=currentBook.pages.splice(draggedIndex,1);currentBook.pages.splice(to,0,moved);currentImageIndex=to;draggedIndex=null;renderThumbnails();showToast('图片顺序已调整');});
  });
}
function setEditMode(value){const next=Boolean(value&&canModifyCurrentBook());if(next&&!editMode)orderSnapshot=currentBook.pages.map(page=>page.id);if(!next)orderSnapshot=null;editMode=next;$('#editHint').classList.toggle('hidden',!editMode);$('#toggleEdit').textContent=editMode?'完成排序':'编辑图片顺序';if(currentBook)renderThumbnails();}
function resetImageOrder(){if(!editMode||!canModifyCurrentBook()||!orderSnapshot)return;const order=new Map(orderSnapshot.map((id,index)=>[id,index]));currentBook.pages.sort((a,b)=>(order.get(a.id)??Number.MAX_SAFE_INTEGER)-(order.get(b.id)??Number.MAX_SAFE_INTEGER));currentImageIndex=0;draggedIndex=null;renderThumbnails();showToast('图片顺序已重置');}
function resetCropPreview(){cropPreview=false;$('#previewCrop').textContent='预览裁切效果';$('#cropHelp').textContent='拖动裁切框移动，拖动四角缩放';}
function openViewer(){const page=currentBook.pages[currentImageIndex];if(!page)return;const sideways=Math.abs(page.rotation)%180===90;cropDraft=null;resetCropPreview();$('#cropPanel').classList.add('hidden');$('#cropOverlay').classList.add('hidden');$('#viewerImage').src=page.src;$('#viewerImage').style.transform=`rotate(${page.rotation}deg) scale(${sideways?'.78':'1'})`;$('#viewerImage').style.clipPath=cropInset(page.crop);$('#viewerPosition').textContent=`${currentImageIndex+1} / ${currentBook.pages.length}`;$('#viewerCaption').textContent=`第 ${currentImageIndex+1} 张答案图片 · ${page.rotation===0?'原始方向':`已旋转 ${page.rotation}°`}${isCropped(page.crop)?' · 已裁切':''}`;$('#viewerModal').classList.remove('hidden');updateViewerButtons();}
function updateViewerButtons(){const first=currentImageIndex===0,last=currentImageIndex===currentBook.pages.length-1;$('#prevImage').disabled=first;$('#nextImage').disabled=last;}
function rotateImage(delta){if(!canModifyCurrentBook())return;const page=currentBook.pages[currentImageIndex];if(!page)return;page.rotation=(page.rotation+delta+360)%360;renderThumbnails();openViewer();showToast(page.rotation===0?'已恢复图片原始方向':`图片已旋转至 ${page.rotation}°`);}
const clamp=(value,min,max)=>Math.min(max,Math.max(min,value));
function updateCropOverlay(){if(!cropDraft)return;const imageRect=$('#viewerImage').getBoundingClientRect(),canvasRect=$('#viewerCanvas').getBoundingClientRect(),overlay=$('#cropOverlay');const left=imageRect.left-canvasRect.left+imageRect.width*cropDraft.left/100,top=imageRect.top-canvasRect.top+imageRect.height*cropDraft.top/100,width=imageRect.width*(100-cropDraft.left-cropDraft.right)/100,height=imageRect.height*(100-cropDraft.top-cropDraft.bottom)/100;Object.assign(overlay.style,{left:`${left}px`,top:`${top}px`,width:`${width}px`,height:`${height}px`});$('#cropDimensions').textContent=`${Math.round(100-cropDraft.left-cropDraft.right)}% × ${Math.round(100-cropDraft.top-cropDraft.bottom)}%`;}
function openCropPanel(){if(!canModifyCurrentBook())return;const page=currentBook.pages[currentImageIndex];if(!page)return;cropDraft={...page.crop};resetCropPreview();$('#viewerImage').style.clipPath='none';$('#cropPanel').classList.remove('hidden');$('#cropOverlay').classList.remove('hidden');requestAnimationFrame(updateCropOverlay);}
function toggleCropPreview(){if(!canModifyCurrentBook()||!cropDraft)return;cropPreview=!cropPreview;$('#cropOverlay').classList.toggle('hidden',cropPreview);$('#viewerImage').style.clipPath=cropPreview?cropInset(cropDraft):'none';$('#previewCrop').textContent=cropPreview?'继续裁切':'预览裁切效果';$('#cropHelp').textContent=cropPreview?'当前为裁切效果预览，点击“继续裁切”返回裁切框':'拖动裁切框移动，拖动四角缩放';if(!cropPreview)requestAnimationFrame(updateCropOverlay);}
function closeCropPanel(){cropDraft=null;resetCropPreview();$('#cropPanel').classList.add('hidden');$('#cropOverlay').classList.add('hidden');}
function startCropDrag(event){if(!cropDraft||!canModifyCurrentBook())return;event.preventDefault();const handle=event.target.dataset.handle||'move',imageRect=$('#viewerImage').getBoundingClientRect(),startX=event.clientX,startY=event.clientY,start={...cropDraft},minSize=12;const onMove=moveEvent=>{if(!canModifyCurrentBook())return;const dx=(moveEvent.clientX-startX)/imageRect.width*100,dy=(moveEvent.clientY-startY)/imageRect.height*100;let next={...start};if(handle==='move'){const moveX=clamp(dx,-start.left,start.right),moveY=clamp(dy,-start.top,start.bottom);next.left=start.left+moveX;next.right=start.right-moveX;next.top=start.top+moveY;next.bottom=start.bottom-moveY;}else{if(handle.includes('w'))next.left=clamp(start.left+dx,0,100-start.right-minSize);if(handle.includes('e'))next.right=clamp(start.right-dx,0,100-start.left-minSize);if(handle.includes('n'))next.top=clamp(start.top+dy,0,100-start.bottom-minSize);if(handle.includes('s'))next.bottom=clamp(start.bottom-dy,0,100-start.top-minSize);}cropDraft=next;updateCropOverlay();};const onUp=()=>{document.removeEventListener('mousemove',onMove);document.removeEventListener('mouseup',onUp);};document.addEventListener('mousemove',onMove);document.addEventListener('mouseup',onUp);}
function fillBookEditor(){$('#editBookName').value=currentBook.name;$('#editBookTextbookVersion').value=currentBook.textbookVersion;$('#editBookSubtitle').value=currentBook.subtitle;$('#editBookGrade').value=currentBook.grade;$('#editBookCourse').value=currentBook.course;}
function refreshBookDetails(){currentBook.cover=bookCover(currentBook.name.slice(0,6),`${currentBook.grade} · ${currentBook.course}`,currentBook.hue);$('#detailTitle').textContent=currentBook.name;$('#detailCover').src=currentBook.cover;$('#detailBookName').textContent=`${currentBook.name} · ${currentBook.subtitle}`;['Isbn','TextbookVersion','Subtitle','Grade','Course','Province'].forEach(k=>$('#detail'+k).textContent=currentBook[k.charAt(0).toLowerCase()+k.slice(1)]);}
function showToast(message){$('#toast p').textContent=message;$('#toast').classList.remove('hidden');clearTimeout(showToast.timer);showToast.timer=setTimeout(()=>$('#toast').classList.add('hidden'),2200);}
function showConfirm(type){if(!canModifyCurrentBook())return;pendingDecision=type;const pass=type==='pass';$('#confirmIcon').textContent=pass?'✓':'×';$('#confirmIcon').className=`confirm-icon ${pass?'':'reject'}`;$('#confirmTitle').textContent=pass?'确认通过审核？':'确认拒绝该图书？';$('#confirmText').textContent=pass?`通过后将把“${currentBook.uploader}”记录为图书上传者。`:'拒绝后将同步状态给 C 端，请填写审核备注。';$('#rejectRemarkField').classList.toggle('hidden',pass);$('#rejectRemark').value='';$('#submitConfirm').textContent=pass?'确认通过':'确认拒绝';$('#submitConfirm').className=`btn ${pass?'success':'danger'}`;$('#confirmModal').classList.remove('hidden');if(!pass)$('#rejectRemark').focus();}

$('#filterForm').addEventListener('submit',e=>{e.preventDefault();const val=id=>$(id).value.trim();filteredBooks=books.filter(b=>(!val('#filterId')||b.id.includes(val('#filterId')))&&(!val('#filterIsbn')||b.isbn.includes(val('#filterIsbn')))&&(!val('#filterName')||b.name.includes(val('#filterName')))&&(!val('#filterUserId')||b.userId.includes(val('#filterUserId')))&&(!val('#filterUploader')||b.uploader.includes(val('#filterUploader')))&&(!val('#filterStatus')||b.status===val('#filterStatus'))&&(!val('#filterGrade')||b.grade===val('#filterGrade'))&&(!val('#filterCourse')||b.course===val('#filterCourse'))&&(!val('#filterProvince')||b.province===val('#filterProvince')));renderRows();showToast(`已查询到 ${filteredBooks.length} 条任务`);});
$('#resetFilters').addEventListener('click',()=>{$('#filterForm').reset();filteredBooks=[...books];renderRows();});
$('#collapseFilters').addEventListener('click',()=>{$('#filterForm').classList.toggle('hidden');$('#collapseFilters').innerHTML=$('#filterForm').classList.contains('hidden')?'展开条件 <span>⌄</span>':'收起条件 <span>⌃</span>';});
$('#refreshTable').addEventListener('click',()=>{renderRows();showToast('列表已刷新');});
$('#backToList').addEventListener('click',()=>{$('#detailView').classList.remove('active');$('#listView').classList.add('active');renderRows();updateSummaries();});
$('#editBookInfo').addEventListener('click',()=>{if(!canModifyCurrentBook())return;fillBookEditor();$('#bookInfoDisplay').classList.add('hidden');$('#bookInfoEditor').classList.remove('hidden');});
$('#cancelBookInfo').addEventListener('click',()=>{$('#bookInfoEditor').classList.add('hidden');$('#bookInfoDisplay').classList.remove('hidden');});
$('#saveBookInfo').addEventListener('click',()=>{if(!canModifyCurrentBook())return;const name=$('#editBookName').value.trim(),subtitle=$('#editBookSubtitle').value.trim(),textbookVersion=$('#editBookTextbookVersion').value;if(!name||!subtitle||!textbookVersion){showToast('图书名称、版本和册次不能为空');return;}Object.assign(currentBook,{name,textbookVersion,subtitle,grade:$('#editBookGrade').value,course:$('#editBookCourse').value});refreshBookDetails();renderRows();$('#bookInfoEditor').classList.add('hidden');$('#bookInfoDisplay').classList.remove('hidden');showToast('图书基本信息已保存');});
$('#toggleEdit').addEventListener('click',()=>{if(!canModifyCurrentBook())return;setEditMode(!editMode);}); $('#finishEdit').addEventListener('click',()=>setEditMode(false));
$('#resetOrder').addEventListener('click',resetImageOrder);
$$('[data-close-modal]').forEach(el=>el.addEventListener('click',()=>$('#viewerModal').classList.add('hidden')));
$('#prevImage').addEventListener('click',()=>{if(currentImageIndex>0){currentImageIndex--;renderThumbnails();openViewer();}}); $('#nextImage').addEventListener('click',()=>{if(currentImageIndex<currentBook.pages.length-1){currentImageIndex++;renderThumbnails();openViewer();}});
$('#rotateLeft').addEventListener('click',()=>rotateImage(-90)); $('#rotateRight').addEventListener('click',()=>rotateImage(90)); $('#resetRotation').addEventListener('click',()=>{if(!canModifyCurrentBook())return;const page=currentBook.pages[currentImageIndex];if(!page||page.rotation===0)return;page.rotation=0;renderThumbnails();openViewer();showToast('已恢复图片原始方向');});
$('#cropImage').addEventListener('click',openCropPanel);
$('#previewCrop').addEventListener('click',toggleCropPreview);
$('#cropOverlay').addEventListener('mousedown',startCropDrag);
$('#resetCrop').addEventListener('click',()=>{if(!canModifyCurrentBook()||!cropDraft)return;cropDraft={top:0,right:0,bottom:0,left:0};if(cropPreview)$('#viewerImage').style.clipPath=cropInset(cropDraft);else updateCropOverlay();});
$('#cancelCrop').addEventListener('click',()=>{closeCropPanel();openViewer();});
$('#applyCrop').addEventListener('click',()=>{if(!canModifyCurrentBook()||!cropDraft)return;const page=currentBook.pages[currentImageIndex];if(!page)return;const appliedCrop={...cropDraft};page.crop=appliedCrop;closeCropPanel();renderThumbnails();openViewer();showToast(isCropped(appliedCrop)?'图片裁切已应用':'图片裁切已重置');});
window.addEventListener('resize',()=>{if(!$('#cropOverlay').classList.contains('hidden'))updateCropOverlay();});
$('#deleteImage').addEventListener('click',()=>{if(!canModifyCurrentBook()||currentBook.pages.length<=1)return;currentBook.pages.splice(currentImageIndex,1);currentImageIndex=Math.min(currentImageIndex,currentBook.pages.length-1);renderThumbnails();openViewer();showToast('图片已删除');});
$('#passBook').addEventListener('click',()=>{if(!$('#bookInfoEditor').classList.contains('hidden')){showToast('请先保存或取消图书信息编辑');return;}showConfirm('pass');}); $('#rejectBook').addEventListener('click',()=>{if(!$('#bookInfoEditor').classList.contains('hidden')){showToast('请先保存或取消图书信息编辑');return;}showConfirm('reject');});
$('#cancelConfirm').addEventListener('click',()=>$('#confirmModal').classList.add('hidden')); $('#submitConfirm').addEventListener('click',()=>{if(!canModifyCurrentBook()||!['pass','reject'].includes(pendingDecision)){$('#confirmModal').classList.add('hidden');return;}const rejectRemark=$('#rejectRemark').value.trim();if(pendingDecision==='reject'&&!rejectRemark){showToast('请填写审核备注');$('#rejectRemark').focus();return;}currentBook.status=pendingDecision==='pass'?'审核通过':'人工审核未通过';currentBook.remark=pendingDecision==='pass'?'':rejectRemark;if(pendingDecision==='pass'&&!currentBook.newBookId)currentBook.newBookId=String(5048700+books.indexOf(currentBook));$('#confirmModal').classList.add('hidden');const st=$('#detailStatus');st.textContent=currentBook.status;st.className=`status ${statusClass[currentBook.status]}`;$('#toggleEdit').classList.add('hidden');$('#viewerToolbar').classList.add('hidden');$('#decisionActions').classList.add('hidden');$('#autosaveText').textContent='当前任务仅支持查看';setEditMode(false);updateSummaries();showToast(pendingDecision==='pass'?`审核通过并完成入库，新图书 ID：${currentBook.newBookId}`:'人工审核未通过，已记录审核备注');pendingDecision=null;});
document.addEventListener('keydown',e=>{if(e.key==='Escape'){$('#viewerModal').classList.add('hidden');$('#confirmModal').classList.add('hidden');}if(!$('#viewerModal').classList.contains('hidden')&&e.key==='ArrowLeft')$('#prevImage').click();if(!$('#viewerModal').classList.contains('hidden')&&e.key==='ArrowRight')$('#nextImage').click();if(!$('#viewerModal').classList.contains('hidden')&&e.key.toLowerCase()==='r')rotateImage(e.shiftKey?-90:90);});
renderRows();updateSummaries();
